language: python
python:
  - "3.6"
branches:
  only:
  - master
# from https://gist.github.com/iedemam/9830045
# I use SSH URLs in my submodules for convenience. However, Travis CI is unable to
# clone from those URLs even though the repositories are public. To fix this, I'm
# simply manipulating the .gitmodules file with sed so it points to the public
# URLs before initializing the submodules.
#
# Hope it saves you some frustration!
#

# disable the default submodule logic
git:
  submodules: false

# use sed to replace the SSH URL with the public URL, then init and update submodules
before_install:
- sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
- git submodule update --init --recursive
install:
- pip install pelican
- pip install Markdown
- pip install typogrify
- pip install bs4
- pip install ghp-import
- pip install jupyter 
script:
# build and publish to github pages
# Github token is configured in travis repo settings
# https://docs.travis-ci.com/user/deployment/pages/
- make travis

